import type { VercelRequest, VercelResponse } from '@vercel/node';
import { getOrCreateBriefing } from './_lib/briefing';
import { loadChatConfig } from './_lib/config';
import { kv } from './_lib/kvClient';
import { createOpenAIResponsesApi } from './_lib/openaiApi';
import { checkRateLimit } from './_lib/rateLimit';

const DEFAULT_TIMEZONE = 'Asia/Kolkata';

/**
 * GET /api/briefing: today's impact briefing, generated by the first request of the day (see spec section 12).
 * 200 {status:'ready', briefing} | 200 {status:'disabled'} | 202 {status:'pending'} | 502 {error}.
 */
export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'GET') {
    res.status(405).json({ error: 'method not allowed' });
    return;
  }

  const forwardedFor = req.headers['x-forwarded-for'];
  const ip =
    (Array.isArray(forwardedFor) ? forwardedFor[0] : forwardedFor)?.split(',')[0]?.trim() ||
    req.socket.remoteAddress ||
    'unknown';

  const limit = checkRateLimit(ip);
  if (!limit.allowed) {
    res.status(429).json({ error: 'too many requests, try again in a few minutes' });
    return;
  }

  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    res.status(200).json({ status: 'disabled' });
    return;
  }

  try {
    const outcome = await getOrCreateBriefing({
      kv,
      api: createOpenAIResponsesApi(apiKey),
      config: loadChatConfig(),
      now: () => new Date(),
      timeZone: process.env.BRIEFING_TIMEZONE || DEFAULT_TIMEZONE,
    });
    switch (outcome.status) {
      case 'ready':
        res.status(200).json({ status: 'ready', briefing: outcome.briefing });
        return;
      case 'disabled':
        res.status(200).json({ status: 'disabled' });
        return;
      case 'pending':
        res.status(202).json({ status: 'pending' });
        return;
      case 'failed':
        res.status(502).json({ error: 'briefing temporarily unavailable' });
        return;
    }
  } catch (err) {
    console.error('briefing endpoint error', err instanceof Error ? err.name : 'unknown error');
    res.status(502).json({ error: 'briefing temporarily unavailable' });
  }
}
